images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:latest"
  - "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID"
logsBucket: "gs://openteams-score-build-logs"
steps:
  # Create the deployment
  # - name: "gcr.io/cloud-builders/curl"
  #   entrypoint: "bash"
  #   env: ["REF_NAME=$REF_NAME", "COMMIT_SHA=$COMMIT_SHA", "BUILD_ID=$BUILD_ID"]
  #   secretEnv: ["GITHUB_TOKEN"]
  #   args: [buildscripts/github-deployment.sh]

  - name: "docker"
    args:
      [
        "build",
        "--cache-from",
        "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:latest",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:latest",
        "--build-arg",
        "REVISION_ID=$REVISION_ID",
        "-f",
        "Dockerfile",
        ".",
      ]
  - name: "docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
      ]
  - name: "docker"
    args:
      ["push", "us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "jobs",
        "deploy",
        "scraper",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=1024Mi",
        "--tasks=100",

        "--parallelism=100",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        # TODO: will need to add GITHUB_TOKEN HERE
        # "--set-secrets=GITHUB_TOKEN=GITHUB_TOKEN:latest",
        "--env-vars-file=env.yml",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "pypi-vulnerabilities",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=3",
        "--memory=1024Mi",
        "--tasks=400",
        "--parallelism=100",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=vulnerabilities,SCORE_ECOSYSTEM=PyPI",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "score",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--command=bash",
        "--args=-c,fastapi run score/app.py --port $$PORT",
        "--allow-unauthenticated",
        "--revision-suffix=$SHORT_SHA",
        "--max-instances=10",
        "--concurrency=20",
        "--memory=2Gi",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "scrape-pypi",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=3",
        "--memory=1024Mi",
        "--tasks=400",
        "--parallelism=100",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=scrape-pypi",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "scrape-pypi-downloads",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=1024Mi",
        "--tasks=1",
        "--parallelism=1",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=scrape-pypi-downloads",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "scrape-conda",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=4Gi",
        "--tasks=100",
        "--parallelism=100",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=conda",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "agg-source-urls",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=4Gi",
        "--tasks=1",
        "--parallelism=1",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=agg-source-urls",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "scrape-git",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=4Gi",
        "--tasks=4000",
        "--parallelism=400",
        "--task-timeout=30m",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=git",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "coalesce",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=4Gi",
        "--tasks=8",
        "--parallelism=8",
        "--task-timeout=30m",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=coalesce",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "jobs",
        "deploy",
        "score",
        "--region=us-west1",
        "--image=us-west1-docker.pkg.dev/$PROJECT_ID/containers/scraper:$REVISION_ID",
        "--max-retries=1",
        "--memory=4Gi",
        "--tasks=1",
        "--parallelism=1",
        "--task-timeout=30m",
        "--service-account=scraper@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars=COMMAND=score",
      ]

  # Mark the deployment as successful
  # - name: "gcr.io/cloud-builders/curl"
  #   entrypoint: "bash"
  #   env:
  #     ["SHORT_SHA=$SHORT_SHA", "BUILD_ID=$BUILD_ID", "PROJECT_ID=$PROJECT_ID"]
  #   secretEnv: ["GITHUB_TOKEN"]
  #   args: [buildscripts/github-deployment-status.sh]
# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
#       env: "GITHUB_TOKEN"
