[[tool.mypy.overrides]]
module = ["strsimpy.*"]
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = ["dacite.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pandas.*"]
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = ["cvss.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pyarrow.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["fsspec.*"]
ignore_missing_imports = true


[tool.vulture]
# exclude = ["*file*.py", "dir/"]
ignore_decorators = ["@app.middleware", "@app.get", "@field_serializer"]
paths = ["score", "whitelist.py"]


[tool.pytest.ini_options]
env = ["CACHE_LOCATION = /tmp", "K_REVISION = test"]


[tool.pyright]
