name: "Annotate Requirements"
description: "Annotates the requirements.txt file using the Score API"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  package-ecosystem:
    description: "The package manager ecosystem to annotate. Currently supports 'pip'."
    required: true
  # requirements-path:
  #   description: "Path to the requirements.txt file to annotate."
  #   required: false
  #   default: "requirements.txt"
  # verbose:
  #   description: "Set to true to enable detailed logging."
  #   required: false
  #   default: "false"