name: Requirements Check Action

on: [push]

jobs:
  requirements_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies using Score
        uses: openteamsinc/score@v3
        with:
          package-ecosystem: pip
          directory: '.'

      - name: Display Notice with Requirements
        run: |
          if [ -f requirements.txt ]; then
            LINE=1
            while IFS= read -r package; do
              echo "::notice file=requirements.txt,line=$LINE,col=1,endColumn=${#package}::Found package: $package"
              LINE=$((LINE + 1))
            done < requirements.txt
          else
            echo "::error::requirements.txt file not found"